[2025-06-11T12:04:59.284+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-11T12:04:59.319+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: homework_taxi_pipeline.question_5_train_model manual__2025-06-11T12:01:19.497846+00:00 [queued]>
[2025-06-11T12:04:59.333+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: homework_taxi_pipeline.question_5_train_model manual__2025-06-11T12:01:19.497846+00:00 [queued]>
[2025-06-11T12:04:59.334+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-06-11T12:04:59.352+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): question_5_train_model> on 2025-06-11 12:01:19.497846+00:00
[2025-06-11T12:04:59.369+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=678) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-11T12:04:59.371+0000] {standard_task_runner.py:72} INFO - Started process 687 to run task
[2025-06-11T12:04:59.373+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'homework_taxi_pipeline', 'question_5_train_model', 'manual__2025-06-11T12:01:19.497846+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_homework.py', '--cfg-path', '/tmp/tmpiuyyblem']
[2025-06-11T12:04:59.376+0000] {standard_task_runner.py:105} INFO - Job 7: Subtask question_5_train_model
[2025-06-11T12:04:59.441+0000] {task_command.py:467} INFO - Running <TaskInstance: homework_taxi_pipeline.question_5_train_model manual__2025-06-11T12:01:19.497846+00:00 [running]> on host e64a68750d42
[2025-06-11T12:04:59.556+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='homework' AIRFLOW_CTX_DAG_ID='homework_taxi_pipeline' AIRFLOW_CTX_TASK_ID='question_5_train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-06-11T12:01:19.497846+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-11T12:01:19.497846+00:00'
[2025-06-11T12:04:59.558+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-06-11T12:04:59.576+0000] {logging_mixin.py:190} INFO - Question 5: Training linear regression model...
[2025-06-11T12:04:59.644+0000] {logging_mixin.py:190} WARNING - 2025/06/11 12:04:59 INFO mlflow.tracking.fluent: Experiment with name 'homework-taxi-experiment' does not exist. Creating a new experiment.
[2025-06-11T12:05:00.625+0000] {logging_mixin.py:190} WARNING - 2025/06/11 12:05:00 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-06-11T12:05:26.804+0000] {logging_mixin.py:190} INFO - âœ… Question 5 Answer: Model intercept = 23.85
[2025-06-11T12:05:33.799+0000] {logging_mixin.py:190} INFO - MLflow run_id: 10e90770e2ce425a8e7a57d92ca1a159
[2025-06-11T12:05:34.222+0000] {python.py:240} INFO - Done. Returned value was: 23.849501496528802
[2025-06-11T12:05:34.260+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-06-11T12:05:34.261+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=homework_taxi_pipeline, task_id=question_5_train_model, run_id=manual__2025-06-11T12:01:19.497846+00:00, execution_date=20250611T120119, start_date=20250611T120459, end_date=20250611T120534
[2025-06-11T12:05:34.521+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-06-11T12:05:34.572+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-11T12:05:34.582+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
